### ISSUE TITLE
{"code":401,"message":"expire missing"}

### ISSUE THREAD

**Issue by siyue666** [alist-org/alist-proxy#18]
域名和ip都试过了，v3也是在设置里复制的令牌，怎么搞都不行

**Comment by GQingS** [comment]
最后解决问题了吗

**Comment by siyue666** [comment]
> 最后解决问题了吗

地址好像必须得是域名，反正不能带端口

**Comment by stevenliuit** [comment]
我的也是这个错误

**Comment by stevenliuit** [comment]
> > 最后解决问题了吗
> 
> 地址好像必须得是域名，反正不能带端口

我的是域名+端口的 不行

**Comment by Iuleoo** [comment]
我现在也是这样了，同样的配置，没有变动。之前都可以用，突然就这样了

**Comment by Guichen1210** [comment]
我也是同样的问题，现在也是显示 [{“code”：401，“message”：“expire missing”}](https://github.com/alist-org/alist-proxy/issues/18#top)

**Comment by wimotek** [comment]
看了下代码. 直接访问 . 显示 expire missing 应该是正常的.   现在下载报erro 1101  不知道是哪里问题.    日志如下:

{
  "outcome": "exception",
  "scriptName": "onedrive",
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON",
      "timestamp": 1684992161910
    }
  ],
  "logs": [],
  "eventTimestamp": 1684992161801,
  "event": {

**Comment by mojiez** [comment]
> 看了下代码. 直接访问 . 显示 expire missing 应该是正常的. 现在下载报erro 1101 不知道是哪里问题. 日志如下:
> 
> { "outcome": "exception", "scriptName": "onedrive", "exceptions": [ { "name": "SyntaxError", "message": "Unexpected token '<', "\r\n<h"... is not valid JSON", "timestamp": 1684992161910 } ], "logs": [], "eventTimestamp": 1684992161801, "event": {
> 
> 看日志. token格式不对. 这个token不知道是哪里的. onedrive正常访问 代理的token也是按要求填 的V3设置里面的令牌

请问这个日志在哪里看的，现在还是只能用域名吗？
